### ISSUE TITLE
Including tag on a merge commit

### ISSUE THREAD

**Issue by tlimpanont** [conventional-changelog/conventional-github-releaser#22]
Please show me a way to include a tag on a merge commit. How do I do that with gitRawCommit.opts?

**Comment by stevemao** [comment]
https://github.com/conventional-changelog/conventional-changelog-ember/blob/master/index.js#L61

**Comment by hbetts** [comment]
I actually ran into this issue myself on Monday while using `semantic-release-gitlab`.

Because the last commit will always be a merge commit (it's the default configuration for new GitLab projects), and because `semantic-release-gitlab` always creates the tag on the last commit, its the merge commit that contains the tag.

A very simple repository (Using a standard `git merge branch/name --no-ff` to create a merge commit) is able to demonstrate this issue:

```bash
(22:37 CDT)-(git::master)--> git log --graph
*   commit 084f9029663eb5fdb28108194d95a6c47f95e851
|\  Merge: 8c9780a ab55557
| | Author: Hutson Betts <hutson@hyper-expanse.net>
| | Date:   Tue Aug 9 21:31:38 2016 -0500
| |
| |     Merge branch 'feat/package/author'
| |
| * commit ab55557244b20a0186bc1d5f3125e23afc415808
|/  Author: Hutson Betts <hutson@hyper-expanse.net>
|   Date:   Tue Aug 9 21:25:46 2016 -0500
|
|       feat(package): add author
|
|       Add myself to the author list.
|
* commit 8c9780a0e0929681b7d097568a05f3222fafe5cd
| Author: Hutson Betts <hutson@hyper-expanse.net>
| Date:   Tue Aug 9 21:24:30 2016 -0500
|
|     feat(package): add descriptive project keyword
|
|     Add a descriptive project keyword to project's `package.json` file.
|
* commit f41ceb7792b7d545ed61284e6d3458b0dcebf41e
  Author: Hutson Betts <hutson@hyper-expanse.net>
  Date:   Tue Aug 9 21:23:51 2016 -0500

      chore(package): initial commit

      Initial project commit.
```

@stevemao you suggested setting `noMerges` to `null`, but it seems that doesn't actually work.

I ended up needing to set the option `merges` to `null` to have merge commits included. (Props to @tlimpanont for demonstrating that option in part-up/part-up#622)

Turns out, though, that you can't pass `merges` or `noMerges` to `conventional-github-releaser` or `conventional-gitlab-releaser` because if `releaseCount` is set to anything but `0`, `gitRawCommitsOpts` will be replaced: https://github.com/conventional-changelog/conventional-github-releaser/blob/73c27d93958a4cdf5ed857a3c2819ad804d7d17f/index.js#L76

I will be releasing a new version of `conventional-gitlab-releaser` with the `gitRawCommitsOpts` assigned in the following manner:

```javascript
gitRawCommitsOpts = assign(gitRawCommitsOpts, {
  from: tags[releaseCount]
});
```

That allows for `merges` to be set to `null` by consumers of `conventional-gitlab-releaser`.

**Comment by hbetts** [comment]
This is the change I eventually made to `conventional-gitlab-releaser`: https://gitlab.com/hutson/conventional-gitlab-releaser/compare/c0e50b1a7b18410323961b0badc11af8ea8119a9...master

**Comment by stevemao** [comment]
> Turns out, though, that you can't pass merges or noMerges

It bit me too. I'm fine to make that change.

**Comment by tlimpanont** [comment]
@hbetts ahh very nice, thanks guys!
