### ISSUE TITLE
Not compatible with node 7.0 and node 8.0??

### ISSUE THREAD

**Issue by neoziro** [conventional-changelog/conventional-github-releaser#45]
In package.json, I can read it:

```json
"engines": {
  "node": "^6.9.0 || ^4.2.0",
  "npm": "^4.0.0 || ^3.0.0 || ^2.1.9"
}
```

I am using node v8.0.0, I have the following error:

```
error conventional-github-releaser@1.1.10: The engine "node" is incompatible with this module. Expected version "^6.9.0 || ^4.2.0".
```

Can you remove engines section from package.json?

**Comment by hbetts** [comment]
@neoziro thank you for reporting the issue.

May I assume you're using the Yarn package manager?

I've seen this exact issue from others, including myself, given that I also use `yarn`, since Yarn treats incompatible node versions as a hard failure instead of a warning.

There's a discussion on the Yarn GitHub project regarding that behavior - https://github.com/yarnpkg/yarn/issues/1102

A workaround is to pass `--ignore-engines` to yarn install.

Since there has been no upstream movement on a resolution to the strict enforcement of the engines property by Yarn, I've gone ahead and relaxed the version range constraint in this project's `package.json` file.

The version constraint now specifies all versions of Node greater than, or equal to, 4, and greater than, or equal to, npm 2.

**Comment by tinesoft** [comment]
Was about to report that issue as well, thanks @hbetts  for the promtness and detailed explanation!

**Comment by hbetts** [comment]
Version `1.1.11` has been published.

(At some point I'll set this project up with `semantic-release` so that fixes go out just a tad bit faster)

**Comment by neoziro** [comment]
@hbetts thank you for the fix
