### ISSUE TITLE
Running on CI/CD

### ISSUE THREAD

**Issue by ajsb85** [conventional-changelog/conventional-github-releaser#48]
Dear @stevemao

We have an issue with Travis CI / Circle CI.
Always error when the command success.

We solve it with these args:

`conventional-github-releaser -p angular -t $GH_TOKEN -r 0 2> /dev/null || true`

Best regards.

**Comment by hbetts** [comment]
@ajsb85 could you please provide the output of `conventional-github-releaser`?

I believe the error may be caused by this change that I introduced - https://github.com/conventional-changelog/conventional-github-releaser/commit/7c1e4d911a4d793bb7d7489d55084704795ac24c

It technically fixes another bug by correctly failing when requests to GitHub fail, but I did not correctly update the CLI to handle the change in the API.

A fixed was [added to the GitLab version](https://gitlab.com/hyper-expanse/conventional-gitlab-releaser/commit/3d8b26155aa4de8f5dab237d91e2d06665365484) but it has not been ported to this project yet.

**Comment by hbetts** [comment]
Thanks to a bug fix submitted by @danez, version [v1.1.13](https://github.com/conventional-changelog/conventional-github-releaser/releases/tag/v1.1.13) has been released to address this issue.
